#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "面试评测模板 — 端到端烟测"

# 本脚本引导你（真人）在真实 GitHub 账号 + Docker 环境走一遍完整烟测：
# 候选人从 "Use this template" 到在 Actions 运行记录里看到得分面板。
# 纯操作引导，无任何密钥/环境变量配置。

# ── Stage 1: Use this template 创建派生仓 ────────────────────────────────
stage "Use this template 创建派生仓"
say "这一步在浏览器里把模板仓复制到你自己的 GitHub 账号下。"
open_url "https://github.com/Boyuan-Autograder/interview-autograding-template"
step "在模板仓页面右上角点击 'Use this template' 按钮。"
step "在 'Owner' 选择你的账号，为仓库命名（例如 interview-autograding-smoke）。"
step "点击 'Create repository from template' 创建派生仓。"
pause "派生仓创建好后，回到终端继续。"

# ── Stage 2: clone 派生仓到本地 ──────────────────────────────────────────
stage "Clone 派生仓到本地"
say "把你的派生仓克隆到本地，并进入它的目录。"
step "打开你的派生仓页面，点击绿色 'Code' 按钮，复制 clone 地址。"
say "然后在你本地终端执行："
step "git clone <你的派生仓地址>"
step "cd <clone 出来的目录>"
pause "clone 完成并进入目录后，回到终端继续。"

# ── Stage 3: 安装依赖 ─────────────────────────────────────────────────────
stage "安装依赖 (npm install)"
say "在派生仓目录内安装评测工具依赖。"
step "运行：npm install"
note "应输出 'added 1 package'，安装 @boyuan-autograder/interview-autograder。"
pause "npm install 成功后，回到终端继续。"

# ── Stage 4: 复制并完成 Makefile ──────────────────────────────────────────
stage "复制并完成 Makefile"
say "Task 4 的工作区在 task4/ 子目录。先复制模板，再补完 TODO。"
step "运行：cd task4 && cp starter_makefile Makefile"
step "编辑 task4/Makefile，完成所有标记 TODO 的部分（可 grep -rn \"TODO\" 定位）。"
note "若跳过此步，Task 4 会得 0 分——烟测仍可继续，但建议补完以完整验证。"
pause "Makefile 完成后，回到终端继续。"

# ── Stage 5: 完成 Task 5 的 Git 工作流 ────────────────────────────────────
stage "完成 Task 5 的 Git 工作流"
say "Task 5 需要你用一个真实 Git 工作流修复 task5/greet.sh 的 bug 并合回 main。"
step "运行：git checkout -b task5-git"
step "修复 task5/greet.sh 的变量名 typo（把 \$nam 改成 \$name）。"
step "运行：git add task5/greet.sh && git commit -m \"task5: 修复 greet.sh typo\""
step "运行：git checkout main && git merge task5-git"
note "若跳过此步，Task 5 会得 0 分——烟测仍可继续，但建议补完以完整验证。"
pause "Task 5 工作流完成后，回到终端继续。"

# ── Stage 6: 运行评测 ─────────────────────────────────────────────────────
stage "运行评测 (npx autograding grade)"
say "在仓库根运行评测，五个 task 会依次执行。"
step "运行：npx autograding grade"
step "Task 3 会逐题在终端提问选择题（共 15 题），键入 A/B/C/D 并回车。"
note "评分结束后仓库根会生成加密报告单 autograding_report.json。"
pause "评测完成、报告单已生成后，回到终端继续。"

# ── Stage 7: 提交并推送报告单 ─────────────────────────────────────────────
stage "提交并推送报告单"
say "把加密报告单 commit 并 push，触发 Actions workflow。"
step "运行：git add autograding_report.json"
step "运行：git commit -m \"提交评测报告\""
step "运行：git push"
pause "push 成功后，回到终端继续。"

# ── Stage 8: Actions 查看 Job Summary 得分面板 ────────────────────────────
stage "Actions 查看得分面板"
say "在派生仓的 Actions 运行记录里查看解密后的得分面板。"
step "回到浏览器，打开你的派生仓页面，点击顶部 'Actions' 标签。"
step "找到最新一次运行记录（应该刚触发），点击进入。"
step "查看 Job Summary：应有总分、各 task 得分、各检查项 pass/fail 明细。"
if confirm "得分面板是否正确展示（总分 + 各 task + 检查明细）？"; then
  say "✅ 烟测通过！候选人从零到看得分的全链路工作正常。"
else
  warn "烟测未通过。请对照 README 的故障排查小节排查问题。"
fi

finish
